/* Generated by           cobc 3.3-dev.0 */
/* Generated from         prog2.cob */
/* Generated at           Jul 15 2026 16:51:09 */
/* GnuCOBOL build date    Jul 05 2026 21:52:41 */
/* GnuCOBOL package date  Jun 15 2026 14:48:00 UTC */
/* Compile command        cobc -g -Wall prog2.cob */

#include <stdio.h>

/* Module reference count */
static unsigned int		cob_reference_count = 0;

/* Module path */
static const char		*cob_module_path = NULL;

/* Call pointers */
static cob_call_union	__MyClass_Constructor;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Module initialization indicator */
static unsigned int	MyClass_initialized = 0;

/* Module structure pointer */
static cob_module	*MyClass_module = NULL;

/* Global variable pointer */
cob_global		*MyClass_cob_glob_ptr;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   2,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   2,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1	= {13, (cob_u8_ptr)"Hello, world!", &a_1};
static const cob_field c_2	= {2, (cob_u8_ptr)"10", &a_3};
static const cob_field c_3	= {2, (cob_u8_ptr)"12", &a_3};

/* TypeInfo for class */
// static TypeInfo TI_MyClass = {"MyClass", "MySuperClass"}; // field 2 is for searching the parent class and loading it

/* VTable for class, should be static */
// vtable_MyClass[N+1] = [&TI_MyClass, func_ptr_to_function_1, func_ptr_to_function_N];


#define cob_nop	if (!module) cob_nop

